### ISSUE TITLE
Support for html tags format

### ISSUE THREAD

**Issue by siddharthkp** [Download/preact-helmet#17]
Does `preact-helmet` support html tags like react-helmet?

https://github.com/nfl/react-helmet#example: 

```js
<Helmet>
  <meta charSet="utf-8" />
  <title>My Title</title>
  <link rel="canonical" href="http://mysite.com/example" />
</Helmet>
```

**Comment by Download** [comment]
Unfortunately, not (yet).

When I ported Helmet it was at 4.x. They added these new features later. I'll probably port the new version at some point but I don't have the time atm. PRs are always welcome of course!  ;)

**Comment by siddharthkp** [comment]
@Download How should I go about it? If I know the diff between the 2 repos, it can hopefully be automated and always be in sync with react-helmet (at least minor versions)

**Comment by Download** [comment]
Both React Helmet as well as Preact itself have gone up major versions.

If you want to try it, just fork React Helmet v5 and change it to work with Preact. You can peek in the v4 version of the port to see how I dealt with some of the differences. That's how I would do it at least.

**Comment by siddharthkp** [comment]
@Download oh okay. Thanks, I'm going to try that.

**Comment by Download** [comment]
@siddharthkp 

So more people are [requesting](https://github.com/Download/preact-helmet/issues/18) this.
I left you a bit dangling the previous time. Sorry about that.
It would probably help a lot if you didn't have to start from scratch  :)

Look here for some guidance and I'll try to help out getting you started:
https://github.com/Download/preact-helmet/issues/25

**Comment by siddharthkp** [comment]
No worries, https://github.com/Download/preact-helmet/issues/25 is super useful
