### ISSUE TITLE
Add more collaborators?

### ISSUE THREAD

**Issue by siddharthkp** [Download/preact-helmet#20]
Hey,

I see that this project is not in sync with react-helmet anymore. There are also a few open pull requests.

Would you like to add more collaborators to the project? I'd be happy to help in both those aspects.

Cheers!

**Comment by Download** [comment]
Yes, I am definitely ok with that!

React-Helmet went through some significant changes to get to their next major version and I haven't had the time to do anything about it. If you'd like to help out you have my blessing!

@ooade Are you also ok with this?

EDIT: @ooade I decided to go ahead and add @siddharthkp , thinking that if you did not agree you'd probably have said it. If that was to quick of me, let me know.

**Comment by Download** [comment]
@siddharthkp Check it!
https://github.com/Download/preact-helmet/invitations

**Comment by siddharthkp** [comment]
Thanks!

**Comment by Download** [comment]
@siddharthkp Is it working for you? I did not yet see you in the list of collaborators

**Comment by siddharthkp** [comment]
Yep, it worked.

**Comment by ooade** [comment]
Yeah. I'm okay with it :) 
I'll go ahead and close this ;)
