### ISSUE TITLE
Package.json version out of date

### ISSUE THREAD

**Issue by Download** [Download/preact-helmet#26]
https://github.com/Download/preact-helmet/blob/v4.0.0-alpha-3/package.json#L4

I just ran npm install and saw the old version number.
Was it possible to `npm publish` this?

**Comment by ooade** [comment]
Oh! Yeah... Add me to list of collaborators on npm to fix that?? 
ooade96@gmail.com

**Comment by Download** [comment]
@ooade  Ah sorry, I never realized you need to be added there as well.
Done now!  👍
